# Generated by Django 4.2 on 2024-11-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Paciente')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del Paciente')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('cantidad_sesiones', models.IntegerField(verbose_name='Cantidad de Sesiones')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('hora_cita', models.TimeField(verbose_name='Hora de la Cita')),
                ('patologia', models.TextField(blank=True, verbose_name='Patología')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created'],
            },
        ),
    ]
