# Generated by Django 4.2 on 2024-11-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_termino',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hora_cita',
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Sesión')),
                ('hora', models.TimeField(verbose_name='Hora de Sesión')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
