# Generated by Django 4.2 on 2024-11-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paciente_estado_paciente_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='asistencia',
            field=models.BooleanField(default=False, verbose_name='Asistencia'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
