# Generated by Django 4.2 on 2024-11-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sesion_asistencia_sesion_observacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_termino',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='asistencia',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='observacion',
        ),
        migrations.AddField(
            model_name='sesion',
            name='asistio',
            field=models.BooleanField(default=False, verbose_name='¿Asistió?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cantidad_sesiones',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Sesiones'),
        ),
    ]
