# Generated by Django 4.2 on 2024-11-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sesion_options_remove_paciente_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='asistio',
            field=models.BooleanField(default=False, verbose_name='Asistió'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Sesión'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Sesión'),
        ),
    ]
