# Generated by Django 4.2 on 2024-12-03 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import gestkin.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sesion_observaciones_alter_sesion_asistio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['fecha', 'hora'], 'verbose_name': 'Sesión', 'verbose_name_plural': 'Sesiones'},
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='asistio',
        ),
        migrations.AddField(
            model_name='sesion',
            name='asistencia',
            field=models.BooleanField(default=False, verbose_name='Asistencia'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('No Terminado', 'No Terminado')], default='En Proceso', max_length=20, verbose_name='Estado de la Sesión'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[gestkin.core.models.validar_rut], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de la Sesión'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='hora',
            field=models.TimeField(default='00:00', verbose_name='Hora de la Sesión'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de la Sesión'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.paciente', verbose_name='Paciente'),
        ),
    ]
