# Generated by Django 4.2 on 2024-12-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sesion_options_remove_sesion_asistio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Terminado', 'Terminado')], default='En Proceso', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('No Terminado', 'No Terminado')], default='En Proceso', max_length=20),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
