# Generated by Django 4.2 on 2024-12-04 00:36

from django.db import migrations, models
import gestkin.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_paciente_estado_alter_paciente_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[gestkin.core.models.validar_rut], verbose_name='RUT'),
        ),
    ]
