# Generated by Django 4.2 on 2024-12-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_archivopaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='comentario_asistencia',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario de Asistencia'),
        ),
    ]
